language:
    - objective-c

before_install:
    - brew update

install:
    - brew install autoconf automake libtool

before_script:
  - ./bootstrap
  - CFLAGS="-std=c99 -Wall -Wextra -Wno-unused-parameter" ./configure
  - make

script:
  - make check


notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
